# Tous les thèmes

GET http://localhost:3000/v1/api/themes

###

# Un seul thème
GET http://localhost:3000/v1/api/themes/3


###
# Un seul thème qui n'existe pas 

GET http://localhost:3000/v1/api/themes/5

###

# Toutes les missions 

GET http://localhost:3000/v1/api/missions

###

# Toutes les missions pour un thème donné 

GET http://localhost:3000/v1/api/themes/3/missions

###

# Toutes les missions pour un thème donné 

GET http://localhost:3000/v1/api/themes/2/missions

###

# Tous les missions 

GET http://localhost:3000/v1/api/themes/2/missions

###

# Un utilisteur interne dans notre api
GET http://localhost:3000/v1/api/users/1

###

# Tous les utilisateurs
GET http://localhost:3000/v1/api/users

###

# Les valeurs de case à cocher pour l'utilisateur 3
GET http://localhost:3000/v1/api/missions/users/3

###

# La valeur de la case à cocher pour la mission 5 et l'utilisateur 3
GET http://localhost:3000/v1/api/missions/5/users/3

###

# La valeur de la case à cocher pour la mission 7 et l'utilisateur 3 
GET http://localhost:3000/v1/api/missions/7/users/3

###

# Insérer une case cochée en bdd pour la mission 12 et l'utilisateur 3 
POST http://localhost:3000/v1/api/missions/12/users/3
Content-Type: application/json

{
    "is_checked": true,
    "mission_id": 12,
    "user_id": 3
}
